services:
  api-server:
    build: ./api-server
    restart: unless-stopped
    ports:
      - "5555:5555"
    env_file:
      - ./.env
    depends_on:
      - mongo
      - redis
    volumes:
      - ./api-server:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - rag-net

  python-worker:
    build: ./python-worker
    restart: unless-stopped
    ports:
      - "5001:5001"
    env_file:
      - ./.env
    depends_on:
      - mongo
      - redis
    volumes:
      - ./python-worker:/usr/src/app
    networks:
      - rag-net

  mongo:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - rag-net

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - rag-net

networks:
  rag-net:
    driver: bridge

volumes:
  mongo-data: